### ISSUE TITLE
using proxy.yml doesn't send dns requests through proxy

### ISSUE THREAD

**Issue by Htb2050** [shiinarimo/Rules#1]
Hey, I though The proxy provider was an option to tunnel dns in clash through the proxy servers but it still shows the same local CDN that is shown if the dns is directly being contacted. Is there any way to tunnel the dns through the proxy server too?

**Comment by shiinarimo** [comment]
That provider is just for local dns servers such as smartdns.Clash is actually using dns forwarding,if the domains are not matched, it will automatically contact the dns without proxy.
So if you want to tunnel dns through the proxy server,the traffic other than dns will need to bypass the same instance of clash.And your proxy server will also need to support udp forwarding.
